import type { ReactElement } from 'react';
import { secsToTimecode } from '../../lib/time';
import type { FilmstripTileStyle } from '../../media/thumbnails';

export interface FilmstripSprite {
  url: string;
  tiles: FilmstripTileStyle[];
}

export interface FilmstripProps {
  /** YouTube's 4 free i.ytimg.com stills -- each its own full image (source.filmstripUrls). */
  urls?: string[];
  /** The mediabunny-generated sprite for a local/URL source (Task 5): one composited image plus
   * per-tile CSS cropping it into individual frames (buildFilmstripTileStyles). Mutually
   * exclusive with `urls` -- a given source populates exactly one of the two. */
  sprite?: FilmstripSprite;
}

/**
 * Renders the strip of thumbnail tiles under the timeline, from whichever channel the current
 * source populated: individual image URLs (YouTube) or one sprite image cropped per tile
 * (everything else, generated by generate_thumbnails via media/thumbnails.ts).
 */
export function Filmstrip({ urls, sprite }: FilmstripProps): ReactElement {
  if (sprite) {
    if (sprite.tiles.length === 0) return <></>;
    return (
      <div className="flex h-11 flex-none gap-[3px] overflow-hidden rounded-token">
        {sprite.tiles.map((tile, i) => (
          <div
            key={`${tile.time}-${i}`}
            role="img"
            aria-label={`Frame preview at ${secsToTimecode(tile.time)}`}
            className="h-full flex-1 bg-no-repeat"
            style={{ backgroundImage: `url(${sprite.url})`, backgroundPosition: tile.backgroundPosition, backgroundSize: tile.backgroundSize }}
          />
        ))}
      </div>
    );
  }

  if (!urls || urls.length === 0) return <></>;
  return (
    <div className="flex h-11 flex-none gap-[3px] overflow-hidden rounded-token">
      {urls.map((url, i) => (
        <img
          key={url}
          src={url}
          alt={`Frame preview ${i + 1}`}
          crossOrigin="anonymous"
          className="h-full flex-1 object-cover"
        />
      ))}
    </div>
  );
}
