import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { ALL_FORMATS, BufferSource, Input } from 'mediabunny';

// Guards the committed tests/fixtures/cuts.mp4 (generated by scripts/make-fixture-video.ts)
// against accidental corruption or regeneration drift, since every later task's e2e tests
// depend on its exact shape (duration, dimensions, one video + one audio track).
describe('tests/fixtures/cuts.mp4', () => {
  it('is a small, exactly-8-second 640x360 clip with one video and one audio track', async () => {
    const bytes = await readFile(path.resolve(import.meta.dirname, '../fixtures/cuts.mp4'));
    expect(bytes.byteLength).toBeLessThanOrEqual(1.5 * 1024 * 1024);

    const input = new Input({ formats: ALL_FORMATS, source: new BufferSource(bytes.buffer as ArrayBuffer) });
    const duration = await input.computeDuration();
    expect(duration).toBeCloseTo(8.0, 1);

    const video = await input.getPrimaryVideoTrack();
    const audio = await input.getPrimaryAudioTrack();
    expect(video).not.toBeNull();
    expect(audio).not.toBeNull();
    expect(await video!.getDisplayWidth()).toBe(640);
    expect(await video!.getDisplayHeight()).toBe(360);
  });
});
